### ISSUE TITLE
Dependency for Express

### ISSUE THREAD

**Issue by OliverJAsh** [typings/registry#282] opened 2016-04-03 11:18 UTC
I am new to Typings and TypeScript. I want to use the [type definitions for Express](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts), so I ran:

```
typings install express --save --ambient
```

But I noticed these type definitions reference other modules:

```
import * as serveStatic from "serve-static";
import * as core from "express-serve-static-core";
```

So I went ahead and installed type definitions for that module from Typings as well:

```
typings install express-serve-static-core --save --ambient
typings install serve-static --save --ambient
```

However one of those modules also depended on `mime`, so I had to install that too.

Is there any way of telling Typings that `express-serve-static-core` et al are dependencies of `express`, so others won't have to do this?

**Comment by louy** [comment] 2016-04-04 22:52
`typings` should automatically install all dependencies, which include `mime` and `serve-static` in this case. However, that only works for non-ambient typings. We just need to port express from DefinitelyTyped to typings.

**Comment by Fank** [comment] 2016-04-04 22:54
related #102

**Comment by blakeembrey** [comment] 2016-04-04 22:58
@OliverJAsh Pretty much an exact duplicate of https://github.com/typings/typings/issues/342, hopefully you can get some context from there.

**Comment by unional** [comment] 2016-04-09 21:04
Close this in favor of https://github.com/typings/typings/issues/342

**Closed by unional** 2016-04-09 21:04 UTC
Labels: question
