### ISSUE TITLE
installing multiple dependencies does not work

### ISSUE THREAD

**Issue by samvloeberghs** [typings/registry#49] opened 2016-01-18 13:55 UTC
Hi,

Trying to install multiple dependencies at the same time doesn't seem to work:
`typings install jquery foundation-sites --save --ambient `

only installs the first,  `jquery`

You probably now that already, just checking :)

Grtz

**Comment by blakeembrey** [comment] 2016-01-18 18:39
@samvloeberghs Definitely known, the UX and flags aren't really set up to install multiple dependencies at once since you need to confirm the name, etc. in some cases. It's unfortunate since I'd love to get full parity with a package manager, but for now it doesn't. Unless there's a sane way for users to do it.

**Comment by blakeembrey** [comment] 2016-01-26 22:47
By the way, this might be possible to support if we enforce `--source` flag usage. For example, `--source` could default to `ambient` (when `--ambient` is used) and `npm` (when `--ambient` is not used). Thoughts?

**Comment by samvloeberghs** [comment] 2016-01-29 14:38
Just to get my thoughts straight: this is a problem related to the fact that typing are categorized in ambient and plain definitions, right? So basically, for it to work, the installer needs to know if the typings are ambient or not. Would you then ask to provide per typing if it's ambient or not?

I hope my remarks sound clear in any way, still trying to understand stuff here :)

**Comment by blakeembrey** [comment] 2016-01-29 17:42
Not exactly. It's caused by the fact that ambient and plain can be typed to different registries - E.g. plain definitions can be `github`, `common`, `bower`, `npm`, etc. I actually have another suggestion and, if you agree, I think it's a worthwhile compromise - see https://github.com/typings/typings/issues/126.

(Apparently I linked to the wrong issue initially, was meant to link to this one).

**Comment by blakeembrey** [comment] 2016-02-12 23:45
Closing in favour of https://github.com/typings/typings/issues/126

**Closed by blakeembrey** 2016-02-12 23:45 UTC

**Comment by blakeembrey** [comment] 2016-02-12 23:47
This'll be part of 0.7.0, I think. The current scheme in my mind is having default sources configured using `.typingsrc`, and then enabling installation source overrides: `typings install debug ms -S`. Just note that this will complicate your initial example since they are coming from two different sources, but we can enable `typings install dt!jquery global!foundation-sites -SA` - what do you think?
