### ISSUE TITLE
Unable to connect to "https://api.typings.org/search?name=debug&ambient=false"

### ISSUE THREAD

**Issue by mattiLeBlanc** [typings/registry#89] opened 2016-02-06 03:53 UTC
Hi,

I am migrating from TSD to Typings and following instructions:
I have installed it with npm globally. 

When I run `typings install debug --save` I get an error message
```
typings ERR! message Unable to connect to "https://api.typings.org/search?name=debug&ambient=false"
typings ERR! caused by getaddrinfo ENOTFOUND api.typings.org api.typings.org:443

typings ERR! cwd /Users/leblanc/www/projectX
typings ERR! system Darwin 15.3.0
typings ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/typings/dist/bin/typings-install.js" "debug" "--save"
typings ERR! node -v v5.3.0
typings ERR! typings -v 0.6.6
typings ERR! code EUNAVAILABLE

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues
```

I am able to install typings however I noticed my IDE (Code or Sublime3) not picking them up like it did with TSD.
So I wondered if that install is required for that. But then it runs into an error.
Does anyone have an idea?

**Comment by blakeembrey** [comment] 2016-02-06 04:01
Looks like a network error, are you behind a proxy at all? There's been a couple of network error people now, so I'd love to get to the bottom of one of these reports. 

As for being picked up, make sure the main or browser file is used. How are you currently using it?

**Comment by mattiLeBlanc** [comment] 2016-02-06 04:11
Hi,
when I manually go the the url via Chrome I get the following output
```
{
results: [
{
name: "debug",
source: "npm",
homepage: "https://www.npmjs.com/package/debug",
description: null
}
],
total: 1
}
```


My tsconfig.json looks like:
```
{
    "filesGlob": [
        "./typings/**/*.d.ts",
        "./server/**/*.ts",
        "./client/**/*.ts"
    ],
    "compilerOptions": {
        "module": "commonjs"
    },
    "compileOnSave": false,
    "buildOnSave": false,
    "files": [
       "./typings/main.d.ts",
       "./typings/ext/angular-meteor/angular-meteor.d.ts",
       "./typings/ext/angular-ui-router/angular-ui-router.d.ts",
       "./typings/ext/angularjs/angular.d.ts",
       "./typings/ext/jquery/jquery.d.ts",
       "./typings/ext/meteor/meteor.d.ts",
       "./typings/ext/tsd.d.ts",
       "./client/views/layout/global.controller.ts"
   ]
}
```

I was actually fiddling around with adding my classes to the files array, see if that works. No luck so far.
When the tds.d.ts was referenced with TSD the IDE's picked it up without a problem.

**Comment by unional** [comment] 2016-02-06 06:25
It seems intermittent. It happens to me once and then went away.

**Comment by blakeembrey** [comment] 2016-02-12 23:44
Closing this issue. Let me know if other network issues pop up.

**Closed by blakeembrey** 2016-02-12 23:44 UTC
Labels: bug

**Comment by BrianO** [comment] 2016-06-20 19:55
I am getting error - typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B20160317120654"
typings ERR! caused by unable to verify the first certificate

This is in the context of Visual Studio and Node Package Manager ;

> typings install

Any help appreciated.
I have tried the _typingsrc file to no avail.

Thanks

**Comment by lucianferoiu** [comment] 2016-07-16 16:27
This is not about old references or any of that, it's about the DNS. `typings.org` is unreachable (only from time to time, I gather, otherwise more people would have noticed)

> ping: cannot resolve typings.org: Unknown host

So it is a real problem, but not sure if this issue should be reopened...
